name: Build

on: [workflow_dispatch, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26"

      - name: Setup Android NDK
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27d # https://developer.android.com/ndk/downloads

      # GradelビルドでGoを使用するため、Goの絶対パスの設定が必要
      - name: Setup Go Path
        run: echo "GO_BINARY=$(which go)" >> $GITHUB_ENV

      # APIレベルは24（Android 7.0 Nougat）以上を指定
      - name: Setup CGO Compiler Path
        run: |
          echo "GO_CC=${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang" >> $GITHUB_ENV

      - name: Setup Gradle Keystore Configuration
        run: |
          echo "RELEASE_KEYSTORE_BASE64=${{ secrets.RELEASE_KEYSTORE_BASE64 }}" >> $GITHUB_ENV
          echo "RELEASE_KEYSTORE_PASSWORD=${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
          echo "RELEASE_KEY_ALIAS=${{ secrets.RELEASE_KEY_ALIAS }}" >> $GITHUB_ENV
          echo "RELEASE_KEY_PASSWORD=${{ secrets.RELEASE_KEY_PASSWORD }}" >> $GITHUB_ENV

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release APK
        run: |
          ./gradlew assembleRelease

      - name: Build Release AAB
        run: |
          ./gradlew bundleRelease

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ github.run_number }}
          path: |
            app/build/outputs/apk/release/*.apk
            app/build/outputs/bundle/release/*.aab
          retention-days: 7
